import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "../globals.css"
import StoreProvider from "@/StoreProvider"
import AppSession from "@/AppSession"
import Header from "@/components/Header"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Amazon App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <AppSession>
        <StoreProvider>
          <body className={inter.className}>
            <Header />
            <div className="mt-[102px]">
            {children}</div>
          </body>
        </StoreProvider>
      </AppSession>
    </html>
  )
}
